### ISSUE TITLE
"Running the contributed command: 'scaffixer.context' failed."

### ISSUE THREAD

**Issue by jacobweber** [alejalapeno/scaffixer#1]
I have this in my settings.json, which I copied from the example:
```
	"scaffixer.templates": [
		{
			"name": "React Component",
			"description": "Create a new React component directory with SCSS module.",
			"location": "/Users/jacobweber/bin/scaffixer-react-component",
			"prompts": ["Name"]
		}
	],
```

And I created a directory at the above location, with a file in it.

When I run the Scaffix command, I immediately get an error "Command 'Scaffix' resulted in an error (Running the contributed command: 'scaffixer.context' failed.)"

The extension log shows:
```
[2020-07-14 10:54:07.450] [exthost] [error] TypeError: Cannot destructure property 'path' of 'undefined' as it is undefined.
    at /Users/jacobweber/.vscode/extensions/alejalapeno.scaffixer-0.0.2/out/index.js:20:86
    at _executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:631:163)
    at _.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:631:538)
    at m._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:801:683)
    at m._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:801:375)
    at m._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:800:14)
    at m._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:798:832)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:797:34
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:849)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:744
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:849)
    at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:240:276)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:237:357
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:233:393)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:232:753
    at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:241:826)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by alejalapeno** [comment]
Apologies for missing the notification of this issue and only seeing it now and thanks for filing it!

I'll dive deeper into this issue but `path` should be received from VSCode any time the context menu is invoked in the File Explorer and shouldn't be undefined.

If you could share your VSCode version/OS it may help me debug the source of the problem.
